In [1]:
import numpy as np

# array = o lista cu toate elementele de acelasi tip


In [2]:
np.array([0,1,2,3])

array([0, 1, 2, 3])

In [3]:
arr = np.array([0,1,2,3])
type(arr), arr.dtype

(numpy.ndarray, dtype('int64'))

In [4]:
arr = np.array([0,1,2,3.0])

type(arr), arr.dtype

(numpy.ndarray, dtype('float64'))

In [5]:
arr = np.arange(10,20)
arr, type(arr), arr.dtype

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 numpy.ndarray,
 dtype('int64'))

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.ones(10) * 2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [9]:
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [10]:
np.array([1,2,3]) ** 2

array([1, 4, 9])

In [11]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
np.arange(100) % 7 

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0,
       1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1,
       2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2,
       3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3,
       4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1])

In [13]:
np.arange(100) % 7  == 0

array([ True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False])

In [15]:
np.arange(100) [np.arange(100) % 7 == 0]

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [19]:
np.arange(100).reshape((4,25))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [24]:
np.random.randint(1,100,3)

array([25,  9, 91])

In [25]:
np.random.randint(1,100,(3,3))

array([[27, 74, 29],
       [98, 19,  9],
       [30, 92, 12]])

In [27]:
np.random.random(3)

array([0.65333288, 0.59927761, 0.0868395 ])

In [29]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [32]:
array = np.random.randint(21,25,50)

In [33]:
array [array ==22]

array([22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22])

In [35]:
array = np.random.randint(2,100,50)
array.max()

96

In [36]:
array = np.random.randint(2,1000,50)
array.max(), array.argmax()

(997, 30)